spring.application.name=resume-ai-backend
# Ollama ???????? API
spring.ai.ollama.base-url=https://ollama.com
spring.ai.ollama.chat.options.model=deepseek-v3.1:671b

# API ???? (????? ?????????? ?????????)
ollama.api.key=4ccbc0b08cce4828a7526cd789d8842c.cpT1HJFs1nSwS9gDT9CfDJjB